customhost = "database-table.cruq67uutafa.ap-south-1.rds.amazonaws.com"
customuser = "admin"
custompass = "adminadmin"
customdb = "employ"
custombucket = "dataemployee001"
customregion = "Asia Pacific (Mumbai) ap-south-1"
